export const detailInfo = [
    {
      id: 1,
      title: "Ghost Rider 2",
      content: "In rural Romania, an alcoholic monk named Moreau warns a nearby monastery about an impending ambush by Roarke's forces. ",
      image: "/ghost_rider.jpg",
      ytLink:"https://www.youtube.com/embed/UUObgxCoUgA",
      rating:"8.2",
      summary:"In rural Romania, an alcoholic monk named Moreau warns a nearby monastery about an impending ambush by Roarke's forces. They seek to kidnap a young boy named Danny and perform a ceremony on him that will allow the aging Roarke to transfer himself into Danny's body. A firefight ensues, and Danny is able to escape with his mother Nadya. Moreau decides to seek out Johnny Blaze, who is currently in hiding to prevent the Rider from running amok.",
      actors:"Nicolas Cage ,Christopher Lambert , Anthony Head, Jacek Koman",
      genre:'Action,Fantasy,Horror',
      age: 16,
     
    },

    {
      id: 2,
      title: "Logan",
      content: "In 2029, no mutants have been born in 25 years, and an aging Logan suffers as his healing ability is failing. ",
      image: "/logan.jpg",
      rating:"8.8",
      ytLink:"https://www.youtube.com/embed/Div0iP65aZo",
      summary:"In 2029, no mutants have been born in 25 years, and an aging Logan suffers as his healing ability is failing. Working as a limousine driver in El Paso, Texas, he and mutant tracker Caliban care for 90-year-old Charles Xavier, founder of the X-Men, in an abandoned smelting plant in northern Mexico. Xavier suffers from dementia that causes him to have destructive telepathic seizures that injured 600 people and killed several X-Men the year prior.",
      actors:"Hugh Jackman,Patrick Stewart,Dafne Keen",
      genre:'Action,Drama,Thriller',
      age: 14,
    },

    {
      id: 3,
      title: "Spiderman 3",
      content: "A year after Otto Octavius' death, Peter Parker plans to propose to Mary Jane Watson, who has made her Broadway musical debut. ",
      image: "/spiderman.jpg",
      rating:"8.0",
      summary:"A year after Otto Octavius' death,[b] Peter Parker plans to propose to Mary Jane Watson, who has made her Broadway musical debut. In Central Park, a meteorite lands near the two, and an extraterrestrial symbiote follows Peter to his apartment by attaching to his motorbike. Harry Osborn, knowing Peter is Spider-Man, seeks to avenge his father's death. Using his father's performance-enhancing gas and Green Goblin technology, he battles Peter to an eventual stalemate, developing partial amnesia. Meanwhile, police pursue escaped convict Flint Marko, who visits his wife and sick daughter before fleeing. ",
      ytLink:"https://www.youtube.com/embed/e5wUilOeOmg",
      actors:"Tobey Maguire , Kirsten Dunst , James Franco , Topher Grace",
      genre:'Action,Romance,Drama',
      age:10,
    },
    {
        id: 4,
        title: "Infinity War",
        content: "Having acquired the Power Stone–one of the six Infinity Stones–from the planet Xandar, Thanos and his lieutenants intercept the spaceship",
        image: "/Infinity_War.jpg",
        rating:"8.5",
        ytLink:"https://www.youtube.com/embed/6ZfuNTqbHE8",
        actors:"Robert Downey Jr.,",
        genre:'Sci-Fi,Thriller,Action,Drama',
        summary:"Having acquired the Power Stone–one of the six Infinity Stones–from the planet Xandar, Thanos and his lieutenants: Ebony Maw, Cull Obsidian, Proxima Midnight, and Corvus Glaive, intercept the spaceship carrying the survivors of Asgard's destruction.[N 1] After subduing Thor, Thanos extracts the Space Stone from the Tesseract, overpowers the Hulk, and kills Loki. Thanos also kills Heimdall after he sends Hulk to Earth using the Bifröst. Thanos and his lieutenants leave, destroying the ship.",
        age:12
    },
    {
        id: 5,
        title: "Exists",
        content: "Brothers Brian and Matt invite a group of friends - Matt's girlfriend Dora and their friends Todd and Elizabeth - on a camping trip to their uncle Bob's cabin in East Texas. ",
        image: "/Exsist.jpg",
        rating:"5.6",
        summary:"Brothers Brian and Matt invite a group of friends - Matt's girlfriend Dora and their friends Todd and Elizabeth - on a camping trip to their uncle Bob's cabin in East Texas. Driving on the forest road, Matt hits something with the car and stops to investigate. The group hears loud animal cries in the distance but dismisses them. Finding the road blocked by a fallen tree, the group continues on foot and reaches the cabin, only to discover that it is dilapidated.",
        ytLink:"https://www.youtube.com/embed/vNKqNBey9MQ",
        actors:"Dora Madison Burge ,Chris Osborn ,Edwards ,Williamson,Samuel Davis,Brian Steele",
        genre:'Horror,Thriller',
        age:18
    },
]